services:
  postgres:
    image: postgres:17.8
    container_name: vn-lms-postgres
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vn_lms -d vn_lms']
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: vn-lms-mailhog
    ports:
      - '${MAIL_SMTP_PORT}:1025'
      - '${MAIL_WEB_PORT}:8025'

volumes:
  pgdata:
