services:
  postgres:
    image: postgres:16-alpine
    container_name: vn-lms-postgres
    environment:
      POSTGRES_DB: vn_lms
      POSTGRES_USER: vn_lms
      POSTGRES_PASSWORD: vn_lms_password
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vn_lms -d vn_lms"]
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: vn-lms-mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  pgdata:

